### ISSUE TITLE
Missing module declaration

### ISSUE THREAD

**Issue by gurkerl83** [vangware/window-open-promise#4]
Using this library for a long time, ignoring the following error whenever I open the file importing the library.

```
Unable to resolve the path to module '@vangware/window-open-promise.' eslint[import/no-unresolved] ...
```

Is it intentional not specifying the module prop to the file which holds all exports? Installing the library, only ```"type": "module"``` is set, but the corresponding module declaration is missing. Adding ```"module": "./dist/index.js"``` after installing the library fixes the problem.

Thx!

**Comment by lukeshiru** [comment]
`"module"` is a non-standard `package.json` field that isn't required for packages to work but was implemented by some build systems in the past. You might want to upgrade `node` to a version that supports the [standard `"exports"`](https://nodejs.org/api/packages.html#exports) field in `package.json`, and if that doesn't do it, I suggest updating your build system to support `"exports"`.

**Comment by gurkerl83** [comment]
It does work without module otherwise I would have asked earlier when stating using the library, I guess it is just a eslint problem then?

**Comment by lukeshiru** [comment]
Most probably, yes. ESLint shouldn't care about packages in your `node_modules`, so maybe a config change to ensure you aren't linting dependencies might do the trick ☺️

**Comment by gurkerl83** [comment]
Not so sure about that... Eslint-import is enabled by default for node_modules, it is not a rule in my project. It validates if someone is consuming a library the right or specified way and this is certainly reasonable. Anyway, I fixed the problem with the following rule, maybe relevant for others.

```
import/ignore:
    - node_modules/@vangware/window-open-promise
```

Thx!
